import { IUnfilledAtt, Optional } from "@utils/base-class/base.interface";
import { AllowNull, Column, Default, ForeignKey, Model, Table } from "sequelize-typescript";
import { Loyalty } from "./Loyalty";
import { Tier } from "./Tier";

type INullableAttr =  IUnfilledAtt;

interface IAutoGeneratedAttr {
  id: number;
}

export interface IModel extends Optional<INullableAttr>, IAutoGeneratedAttr {
  loyaltyId: number;
  tierId: number;
}

export type IModelCreate = Omit<IModel, keyof IAutoGeneratedAttr> & Partial<IAutoGeneratedAttr>;

@Table({
  tableName: 'loyalties_tier',
  indexes: [
    { fields: ['loyalty_id', 'tier_id'], where: { deleted_at: null }},
  ],
  timestamps: false,
})
export class LoyaltyTier extends Model<IModel, IModelCreate> implements IModel {
  declare id: number;

  @ForeignKey(() => Loyalty)
  @AllowNull(false)
  @Column
  loyaltyId: number;

  @ForeignKey(() => Tier)
  @AllowNull(false)
  @Column
  tierId: number;
}