import { IUnfilledAtt, Optional } from "@utils/base-class/base.interface";
import { AllowNull, BelongsTo, BelongsToMany, Column, Default, ForeignKey, Model, Table } from "sequelize-typescript";
import { EHistoryPointType } from "@utils/enum";
import { Member } from "./Member";
import { Loyalty } from "./Loyalty";

export interface INullableAttr extends IUnfilledAtt {
  loyaltyId: number;
};

interface IAutoGeneratedAttr {
  id: number;
}

export interface IModel extends Optional<INullableAttr>, IAutoGeneratedAttr {
  memberId: number;
  transactionId: string;
  transactionDate: Date;
  type: EHistoryPointType;
  point: number;
}

export type IModelCreate = Omit<IModel, keyof IAutoGeneratedAttr> & Partial<IAutoGeneratedAttr>;

@Table({
  tableName: 'member_point_histories',
  paranoid: true,
  indexes: [
    { fields: ['transaction_id'], where: { deleted_at: null }},
  ]
})
export class MemberPointHistory extends Model<IModel, IModelCreate> implements IModel {
  declare id: number;

  @ForeignKey(() => Member)
  @AllowNull(false)
  @Column
  declare memberId: number;

  @ForeignKey(() => Loyalty)
  @Column
  declare loyaltyId: number;

  @AllowNull(false)
  @Column
  declare transactionId: string;

  @AllowNull(false)
  @Column
  declare transactionDate: Date;

  @AllowNull(false)
  @Column
  declare type: EHistoryPointType;

  @AllowNull(false)
  @Default(0)
  @Column
  declare point: number;
  
  @BelongsTo(() => Member)
  declare member: Member;
}