import { IUnfilledAtt, Optional } from "@utils/base-class/base.interface";
import { AllowNull, BelongsTo, BelongsToMany, Column, Default, ForeignKey, HasMany, Model, Table } from "sequelize-typescript";
import { UserLogin } from "./UserLogin";
import { MemberPointHistory } from "./MemberPointHistory";

export interface INullableAttr extends IUnfilledAtt {
  address: string;
  isActive: boolean;
}

interface IAutoGeneratedAttr {
  id: number;
}

export interface IModel extends Optional<INullableAttr>, IAutoGeneratedAttr {
  userId: number;
  name: string;
  phoneNumber: string;
  birthDate: Date;
  joinDate: Date;
  earnedPoint: number;
  redeemedPoint: number;
  remainedPoint: number;
}

export type IModelCreate = Omit<IModel, keyof IAutoGeneratedAttr> & Partial<IAutoGeneratedAttr>;

@Table({
  tableName: 'members',
  paranoid: true,
  indexes: [
    { fields: ['is_active'], where: { deleted_at: null }},
  ]
})
export class Member extends Model<IModel, IModelCreate> implements IModel {
  declare id: number;

  @ForeignKey(() => UserLogin)
  @AllowNull(false)
  @Column
  userId: number;

  @AllowNull(false)
  @Column
  name: string;

  @AllowNull(false)
  @Column
  phoneNumber: string;
  
  @AllowNull(false)
  @Column
  address: string;

  @AllowNull(false)
  @Column
  joinDate: Date;

  @AllowNull(false)
  @Column
  birthDate: Date;

  @AllowNull(false)
  @Default(0)
  @Column
  earnedPoint: number;

  @AllowNull(false)
  @Default(0)
  @Column
  remainedPoint: number;

  @AllowNull(false)
  @Default(0)
  @Column
  redeemedPoint: number;
  
  @AllowNull(false)
  @Default(true)
  @Column
  isActive: boolean;

  @BelongsTo(() => UserLogin)
  user: UserLogin;

  @HasMany(() => MemberPointHistory)
  pointHistories: MemberPointHistory;
}